// GET TODOS

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

// CREATE TODO ITEM

export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE';

// EDIT TODO ITEM

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE';

// DELETE TODO ITEM

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

// MARK ALL TODOS AS COMPLETED

export const MARKS_ALL_AS_COMPLETED_TODOS_REQUEST = 'MARKS_ALL_AS_COMPLETED_TODOS_REQUEST';
export const MARKS_ALL_AS_COMPLETED_TODOS_SUCCESS = 'MARKS_ALL_AS_COMPLETED_TODOS_SUCCESS';
export const MARKS_ALL_AS_COMPLETED_TODOS_FAILURE = 'MARKS_ALL_AS_COMPLETED_TODOS_FAILURE';

// MARK TODO ITEM AS COMPLETED

export const MARK_ITEM_TODO_REQUEST = 'MARK_ITEM_TODO_REQUEST';
export const MARK_ITEM_TODO_SUCCESS = 'MARK_ITEM_TODO_SUCCESS';
export const MARK_ITEM_TODO_FAILURE = 'MARK_ITEM_TODO_FAILURE';

// MARK TODO ITEM AS INCOMPLETED

export const MARK_ITEM_AS_INCOMPLETED_TODO_REQUEST = 'MARK_ITEM_AS_INCOMPLETED_TODO_REQUEST';
export const MARK_ITEM_AS_INCOMPLETED_TODO_SUCCESS = 'MARK_ITEM_AS_INCOMPLETED_TODO_SUCCESS';
export const MARK_ITEM_AS_INCOMPLETED_TODO_FAILURE = 'MARK_ITEM_AS_INCOMPLETED_TODO_FAILURE';

// DELETE ALL COMPLETED TODOS

export const DELETE_COMPLETED_TODO_REQUEST = 'DELETE_COMPLETED_TODO_REQUEST';
export const DELETE_COMPLETED_TODO_SUCCESS = 'DELETE_COMPLETED_TODO_SUCCESS';
export const DELETE_COMPLETED_TODO_FAILURE = 'DELETE_COMPLETED_TODO_FAILURE';
